apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "common.names.fullname" . }}-configmap-editor-binding
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.serviceAccountName }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "common.names.fullname" . }}-configmap-editor
  apiGroup: rbac.authorization.k8s.io